### ISSUE TITLE
RDF::Reader error with subject content

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/fedora-migrate#9]
Certain characters in the subject of a triple are causing RDF::Reader to fail. This happens during RDF datastream conversion, usually in the description field.

**Comment by jcoyne** [comment]
Assad on ruby 2.2, or also in ruby 2.1?

**Comment by jcoyne** [comment]
Damn autocorrect. I meant @awead not Assad

**Comment by awead** [comment]
@jcoyne It happens for me under 2.1.4, but Travis says it's under 2 and 2.1. I'll see about testing 2.2.
